version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - hamzaremmal
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    assignees:
      - hamzaremmal
